package gigago

// Role defines the author of a message in a chat conversation.
type Role string

const (
	// RoleUser represents a message from the end-user.
	RoleUser Role = "user"

	// RoleAssistant represents a message generated by the model.
	RoleAssistant Role = "assistant"

	// RoleSystem provides context or instructions for the model.
	// It typically appears once at the beginning of a conversation.
	RoleSystem Role = "system"
)

// Message represents a single message in a chat conversation.
type Message struct {
	// Role is the author of the message. See the Role type for possible values.
	Role Role `json:"role"`

	// Content is the textual content of the message.
	Content string `json:"content"`
}
